# Generated by Django 4.2.2 on 2023-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50, null=True)),
                ('st_email', models.EmailField(max_length=70, null=True)),
                ('st_phone', models.CharField(max_length=20, null=True)),
                ('st_gender', models.CharField(max_length=70, null=True)),
                ('st_seating', models.CharField(max_length=70, null=True)),
                ('st_diet', models.CharField(max_length=70, null=True)),
                ('st_hand', models.CharField(max_length=70, null=True)),
                ('st_address', models.CharField(max_length=70, null=True)),
                ('st_country', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
