# Generated by Django 4.2.2 on 2023-07-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_hand',
            new_name='st_handicap',
        ),
    ]
