# Generated by Django 4.2.2 on 2023-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_st_hand_student_st_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50, null=True)),
                ('st_email', models.EmailField(max_length=70, null=True)),
                ('st_password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
